defaults: &defaults
  steps:
    - checkout

    # Composer
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "composer.lock" }}
          - v1-dependencies-

    - run:
        name: Composer install
        command: composer install -n --ignore-platform-reqs

    - save_cache:
        key: v1-dependencies-{{ checksum "composer.lock" }}
        paths:
          - ./vendor

    # QA
    - run:
        name: Run PHP CS Fixer
        command: |
          IFS='
          '
          COMMIT_RANGE=$(echo "${CIRCLE_COMPARE_URL}" | cut -d/ -f7)
          if [[ $COMMIT_RANGE != *"..."* ]]; then COMMIT_RANGE="${COMMIT_RANGE}...${COMMIT_RANGE}"; fi
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")
          if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php_cs(\\.dist)?|composer\\.lock)$"; then EXTRA_ARGS=$(printf -- '--path-mode=intersection\n--\n%s' "${CHANGED_FILES}"); else EXTRA_ARGS=''; fi
          ./vendor/bin/php-cs-fixer fix --config=.php_cs --diff --dry-run --stop-on-violation --using-cache=no --verbose ${EXTRA_ARGS}

version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.4.7-cli

    <<: *defaults
